version: "1.0"

services:
  heroes3_api:
    build:
      context: .
    command:
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py crawl &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - hero_db

  hero_db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    env_file:
      - .env