# Generated by Django 4.1.4 on 2022-12-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Creatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("level", models.PositiveIntegerField()),
                (
                    "upgrade",
                    models.PositiveIntegerField(choices=[(0, "Base"), (1, "Upgrade")]),
                ),
                ("attack", models.PositiveIntegerField()),
                ("defence", models.PositiveIntegerField()),
                ("min_damage", models.PositiveIntegerField()),
                ("max_damage", models.PositiveIntegerField()),
                ("hp", models.PositiveIntegerField()),
                ("speed", models.PositiveIntegerField()),
                ("growth", models.PositiveIntegerField()),
                ("ai_value", models.PositiveIntegerField()),
                ("gold", models.PositiveSmallIntegerField()),
                ("wood", models.PositiveSmallIntegerField()),
                ("ore", models.PositiveSmallIntegerField()),
                ("mercury", models.PositiveSmallIntegerField()),
                ("sulfur", models.PositiveSmallIntegerField()),
                ("crystal", models.PositiveIntegerField()),
                ("gems", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HeroesClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="SecondarySkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[(0, "Base"), (1, "Advanced"), (2, "Expert")]
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attack", models.PositiveIntegerField()),
                ("defense", models.PositiveIntegerField()),
                ("power", models.PositiveIntegerField()),
                ("knowledge", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[(0, "Base"), (1, "Advanced"), (2, "Expert")]
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="heroes.creatures",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="heroes.resource",
                    ),
                ),
                (
                    "secondary_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="heroes.secondaryskill",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="heroes.spell"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Heroes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                (
                    "hero_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="heroes.class"
                    ),
                ),
                (
                    "secondary_skill_second",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_skill",
                        to="heroes.secondaryskill",
                    ),
                ),
                (
                    "seondary_skill_first",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_skill",
                        to="heroes.secondaryskill",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="heroes.specialty",
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="heroes.spell"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="creatures",
            name="town",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="heroes.town"
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="skills",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="heroes.skill"
            ),
        ),
    ]
