# Generated by Django 4.1.4 on 2022-12-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Creatures",
            new_name="Creature",
        ),
        migrations.RenameModel(
            old_name="Heroes",
            new_name="Hero",
        ),
        migrations.DeleteModel(
            name="HeroesClass",
        ),
    ]
