# Generated by Django 4.1.4 on 2022-12-10 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0002_rename_creatures_creature_rename_heroes_hero_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hero",
            old_name="seondary_skill_first",
            new_name="secondary_skill_first",
        ),
    ]
