# Generated by Django 4.1.4 on 2022-12-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0004_creature_picture_url_hero_picture_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="town",
            name="name",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
