# Generated by Django 4.1.4 on 2022-12-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0005_alter_town_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creature",
            name="crystal",
        ),
        migrations.RemoveField(
            model_name="creature",
            name="gems",
        ),
        migrations.RemoveField(
            model_name="creature",
            name="mercury",
        ),
        migrations.RemoveField(
            model_name="creature",
            name="ore",
        ),
        migrations.RemoveField(
            model_name="creature",
            name="sulfur",
        ),
        migrations.RemoveField(
            model_name="creature",
            name="wood",
        ),
        migrations.AlterField(
            model_name="creature",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="creature",
            name="upgrade",
            field=models.BooleanField(),
        ),
    ]
