# Generated by Django 4.1.4 on 2022-12-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0006_remove_creature_crystal_remove_creature_gems_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creature",
            name="town",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="heroes.town"
            ),
        ),
    ]
