# Generated by Django 4.1.4 on 2022-12-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0007_alter_creature_town"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secondaryskill",
            name="description",
        ),
        migrations.RemoveField(
            model_name="spell",
            name="description",
        ),
        migrations.AddField(
            model_name="secondaryskill",
            name="description_advance",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="secondaryskill",
            name="description_base",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="secondaryskill",
            name="description_expert",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="spell",
            name="description_advance",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="spell",
            name="description_base",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="spell",
            name="description_expert",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="spell",
            name="magic_school",
            field=models.PositiveIntegerField(
                choices=[(0, "Fire"), (1, "Air"), (2, "Earth"), (3, "Water")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="secondaryskill",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="spell",
            name="level",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="spell",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
