# Generated by Django 4.1.4 on 2022-12-16 18:12

from django.db import migrations, models
import heroes.models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0008_remove_secondaryskill_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secondaryskill",
            old_name="picture_url",
            new_name="picture_url_advance",
        ),
        migrations.AddField(
            model_name="secondaryskill",
            name="picture_url_base",
            field=models.ImageField(null=True, upload_to=heroes.models.image_file_path),
        ),
        migrations.AddField(
            model_name="secondaryskill",
            name="picture_url_expert",
            field=models.ImageField(null=True, upload_to=heroes.models.image_file_path),
        ),
    ]
