# Generated by Django 4.1.4 on 2022-12-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "heroes",
            "0009_rename_picture_url_secondaryskill_picture_url_advance_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="secondaryskill",
            name="level",
        ),
    ]
