# Generated by Django 4.1.4 on 2022-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0010_remove_secondaryskill_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="secondaryskill",
            name="level",
            field=models.PositiveIntegerField(
                choices=[(0, "Base"), (1, "Advanced"), (2, "Expert")], null=True
            ),
        ),
    ]
