# Generated by Django 4.1.4 on 2022-12-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0011_secondaryskill_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secondaryskill",
            old_name="description_advance",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="secondaryskill",
            old_name="picture_url_advance",
            new_name="picture_url",
        ),
        migrations.RemoveField(
            model_name="secondaryskill",
            name="description_base",
        ),
        migrations.RemoveField(
            model_name="secondaryskill",
            name="description_expert",
        ),
        migrations.RemoveField(
            model_name="secondaryskill",
            name="picture_url_base",
        ),
        migrations.RemoveField(
            model_name="secondaryskill",
            name="picture_url_expert",
        ),
    ]
