# Generated by Django 4.1.4 on 2022-12-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "heroes",
            "0012_rename_description_advance_secondaryskill_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondaryskill",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
