# Generated by Django 4.1.4 on 2022-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0013_alter_secondaryskill_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="skills",
        ),
        migrations.AddField(
            model_name="class",
            name="attack",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="defense",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="knowledge",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="power",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
