# Generated by Django 4.1.4 on 2022-12-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0014_remove_class_skills_class_attack_class_defense_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="secondaryskill",
            unique_together={("name", "level")},
        ),
    ]
