# Generated by Django 4.1.4 on 2022-12-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0015_alter_secondaryskill_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="hero",
            name="name",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="hero",
            name="secondary_skill_second",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_skill",
                to="heroes.secondaryskill",
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="spell",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.spell",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="creature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.creature",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.resource",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="secondary_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.secondaryskill",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="spell",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.spell",
                unique=True,
            ),
        ),
    ]
