# Generated by Django 4.1.4 on 2022-12-18 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0016_alter_class_name_alter_hero_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialty",
            name="creature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.creature",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.resource",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="secondary_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.secondaryskill",
            ),
        ),
        migrations.AlterField(
            model_name="specialty",
            name="spell",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="heroes.spell",
            ),
        ),
    ]
