# Generated by Django 4.1.4 on 2022-12-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0017_alter_specialty_creature_alter_specialty_resource_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
