# Generated by Django 4.1.4 on 2022-12-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0018_alter_resource_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="creature",
            old_name="defence",
            new_name="defense",
        ),
        migrations.AlterField(
            model_name="secondaryskill",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
