# Generated by Django 4.1.4 on 2022-12-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes", "0019_rename_defence_creature_defense_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondaryskill",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
